/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import blackhole.Astro;
import blackhole.BlackHole;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author Cristian
 */
public class ViewPanel extends javax.swing.JPanel {
    
    
    public BlackHole bh;
    ArrayList<Astro> astros;
    
    
    /**
     * Creates new form ViewPanel
     */
    public ViewPanel() {
        initComponents();
        bh = new BlackHole(getPreferredSize().getSize().width,getPreferredSize().getSize().height);
        astros = new ArrayList<>();
        boolean right;
        for (int i = 0; i < 700; i++) {
            right = randomNum(2)==1;
            astros.add(new Astro(randomNum(getPreferredSize().width),randomNum(getPreferredSize().height),this,right));
        }
    }    
    
    
    private int randomNum(int max){
        return (int) (Math.random() * max) + 1;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        //g.setColor(Color.yellow);
        //g.fillOval((int)bh.getRect().getCenterX(),(int) bh.getRect().getCenterY(), 10, 10);
        //g.fillRect((int)bh.getRect().getCenterX()-50, (int)bh.getRect().getCenterY()-50, 100, 100);
        for (Astro astro : astros) {
            if (astro.isAlive()) {
                astro.draw(g);
            } else {
                //astros.remove(astro);
            }
            
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1073, 543));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
